import mongoose from 'mongoose';
import { Product } from './models/Product';
import { connectDB } from './config/db';
import dotenv from 'dotenv';

dotenv.config({ path: '.env' });

const mockProducts = [
  {
    slug: "air-max-premium",
    name: "Air Max Premium",
    description: "Experience unparalleled comfort with our Air Max Premium. Featuring advanced cushioning technology and premium materials, these shoes are designed for those who demand excellence in every step.",
    shortDescription: "Premium running shoes with advanced cushioning technology",
    price: 189,
    salePrice: 149,
    rating: 4.9,
    reviewCount: 1284,
    images: [
      "/images/products/air-max-1.jpg",
      "/images/products/air-max-2.jpg",
      "/images/products/air-max-3.jpg",
      "/images/products/air-max-4.jpg",
    ],
    category: "Running" as const,
    brand: "LUXE",
    stock: 45,
    tags: ["running", "premium", "cushioning", "performance"],
    featured: true,
    newArrival: true,
    bestSeller: true,
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "White", hex: "#FFFFFF" },
      { name: "Red", hex: "#EF4444" },
    ],
    sizes: [
      { name: "US 7", available: true },
      { name: "US 8", available: true },
      { name: "US 9", available: true },
      { name: "US 10", available: true },
      { name: "US 11", available: true },
      { name: "US 12", available: false },
    ],
  },
  {
    slug: "ultra-boost-elite",
    name: "Ultra Boost Elite",
    description: "The Ultra Boost Elite combines cutting-edge technology with sophisticated design. Perfect for both athletic performance and casual wear, these shoes deliver exceptional comfort and style.",
    shortDescription: "Elite performance shoes with boost technology",
    price: 219,
    rating: 4.8,
    reviewCount: 956,
    images: [
      "/images/products/ultra-boost-1.jpg",
      "/images/products/ultra-boost-2.jpg",
      "/images/products/ultra-boost-3.jpg",
    ],
    category: "Running" as const,
    brand: "LUXE",
    stock: 32,
    tags: ["running", "boost", "elite", "performance"],
    featured: true,
    newArrival: false,
    bestSeller: true,
    colors: [
      { name: "Navy", hex: "#1E3A8A" },
      { name: "Gray", hex: "#6B7280" },
      { name: "Black", hex: "#000000" },
    ],
    sizes: [
      { name: "US 7", available: true },
      { name: "US 8", available: true },
      { name: "US 9", available: true },
      { name: "US 10", available: false },
      { name: "US 11", available: true },
      { name: "US 12", available: true },
    ],
  },
  {
    slug: "classic-leather",
    name: "Classic Leather",
    description: "Timeless elegance meets modern comfort. Our Classic Leather collection features premium leather construction with cushioned insoles, perfect for everyday wear.",
    shortDescription: "Premium leather casual shoes",
    price: 159,
    salePrice: 129,
    rating: 4.7,
    reviewCount: 743,
    images: [
      "/images/products/classic-leather-1.jpg",
      "/images/products/classic-leather-2.jpg",
      "/images/products/classic-leather-3.jpg",
    ],
    category: "Casual" as const,
    brand: "LUXE",
    stock: 67,
    tags: ["casual", "leather", "classic", "everyday"],
    featured: false,
    newArrival: false,
    bestSeller: true,
    colors: [
      { name: "Brown", hex: "#8B4513" },
      { name: "Black", hex: "#000000" },
      { name: "Tan", hex: "#D2B48C" },
    ],
    sizes: [
      { name: "US 7", available: true },
      { name: "US 8", available: true },
      { name: "US 9", available: true },
      { name: "US 10", available: true },
      { name: "US 11", available: true },
      { name: "US 12", available: true },
    ],
  },
  {
    slug: "basketball-pro",
    name: "Basketball Pro",
    description: "Dominate the court with our Basketball Pro series. Engineered for professional athletes with superior traction, ankle support, and responsive cushioning.",
    shortDescription: "Professional basketball shoes",
    price: 249,
    rating: 4.9,
    reviewCount: 567,
    images: [
      "/images/products/basketball-pro-1.jpg",
      "/images/products/basketball-pro-2.jpg",
      "/images/products/basketball-pro-3.jpg",
    ],
    category: "Basketball" as const,
    brand: "LUXE",
    stock: 28,
    tags: ["basketball", "pro", "court", "performance"],
    featured: true,
    newArrival: true,
    bestSeller: false,
    colors: [
      { name: "Black/Red", hex: "#000000" },
      { name: "White/Blue", hex: "#FFFFFF" },
    ],
    sizes: [
      { name: "US 8", available: true },
      { name: "US 9", available: true },
      { name: "US 10", available: true },
      { name: "US 11", available: true },
      { name: "US 12", available: true },
      { name: "US 13", available: true },
    ],
  },
  {
    slug: "training-elite",
    name: "Training Elite",
    description: "Built for intense training sessions. The Training Elite features breathable mesh, durable construction, and superior stability for all your workout needs.",
    shortDescription: "High-performance training shoes",
    price: 179,
    rating: 4.6,
    reviewCount: 432,
    images: [
      "/images/products/training-elite-1.jpg",
      "/images/products/training-elite-2.jpg",
      "/images/products/training-elite-3.jpg",
    ],
    category: "Training" as const,
    brand: "LUXE",
    stock: 54,
    tags: ["training", "gym", "workout", "performance"],
    featured: false,
    newArrival: false,
    bestSeller: false,
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "Gray", hex: "#6B7280" },
    ],
    sizes: [
      { name: "US 7", available: true },
      { name: "US 8", available: true },
      { name: "US 9", available: true },
      { name: "US 10", available: true },
      { name: "US 11", available: true },
    ],
  },
  {
    slug: "luxury-collection",
    name: "Luxury Collection",
    description: "The pinnacle of footwear craftsmanship. Our Luxury Collection features exotic materials, hand-finished details, and unparalleled comfort for the discerning individual.",
    shortDescription: "Handcrafted luxury footwear",
    price: 499,
    rating: 5.0,
    reviewCount: 189,
    images: [
      "/images/products/luxury-1.jpg",
      "/images/products/luxury-2.jpg",
      "/images/products/luxury-3.jpg",
      "/images/products/luxury-4.jpg",
    ],
    category: "Luxury" as const,
    brand: "LUXE",
    stock: 12,
    tags: ["luxury", "handcrafted", "premium", "exclusive"],
    featured: true,
    newArrival: true,
    bestSeller: false,
    colors: [
      { name: "Gold", hex: "#FFD700" },
      { name: "Silver", hex: "#C0C0C0" },
    ],
    sizes: [
      { name: "US 8", available: true },
      { name: "US 9", available: true },
      { name: "US 10", available: true },
      { name: "US 11", available: false },
    ],
  },
  {
    slug: "lifestyle-essential",
    name: "Lifestyle Essential",
    description: "Perfect for everyday wear. The Lifestyle Essential combines comfort with versatility, making it ideal for work, leisure, and everything in between.",
    shortDescription: "Versatile everyday shoes",
    price: 139,
    salePrice: 109,
    rating: 4.5,
    reviewCount: 892,
    images: [
      "/images/products/lifestyle-1.jpg",
      "/images/products/lifestyle-2.jpg",
    ],
    category: "Lifestyle" as const,
    brand: "LUXE",
    stock: 89,
    tags: ["lifestyle", "everyday", "versatile", "comfort"],
    featured: false,
    newArrival: false,
    bestSeller: true,
    colors: [
      { name: "White", hex: "#FFFFFF" },
      { name: "Black", hex: "#000000" },
      { name: "Beige", hex: "#F5F5DC" },
    ],
    sizes: [
      { name: "US 6", available: true },
      { name: "US 7", available: true },
      { name: "US 8", available: true },
      { name: "US 9", available: true },
      { name: "US 10", available: true },
    ],
  },
  {
    slug: "speed-runner",
    name: "Speed Runner",
    description: "Designed for speed. The Speed Runner features lightweight construction, responsive cushioning, and aerodynamic design for maximum performance.",
    shortDescription: "Lightweight speed running shoes",
    price: 199,
    rating: 4.8,
    reviewCount: 654,
    images: [
      "/images/products/speed-runner-1.jpg",
      "/images/products/speed-runner-2.jpg",
      "/images/products/speed-runner-3.jpg",
    ],
    category: "Running" as const,
    brand: "LUXE",
    stock: 41,
    tags: ["running", "speed", "lightweight", "performance"],
    featured: true,
    newArrival: true,
    bestSeller: false,
    colors: [
      { name: "Neon Yellow", hex: "#FFFF00" },
      { name: "Black", hex: "#000000" },
    ],
    sizes: [
      { name: "US 7", available: true },
      { name: "US 8", available: true },
      { name: "US 9", available: true },
      { name: "US 10", available: true },
      { name: "US 11", available: true },
    ],
  },
  {
    slug: "urban-street",
    name: "Urban Street",
    description: "Street-ready style meets premium comfort. The Urban Street collection features bold designs, durable materials, and all-day comfort for the modern urban explorer.",
    shortDescription: "Bold street-style shoes",
    price: 169,
    rating: 4.6,
    reviewCount: 478,
    images: [
      "/images/products/urban-street-1.jpg",
      "/images/products/urban-street-2.jpg",
    ],
    category: "Casual" as const,
    brand: "LUXE",
    stock: 73,
    tags: ["street", "urban", "bold", "casual"],
    featured: false,
    newArrival: true,
    bestSeller: false,
    colors: [
      { name: "Multi", hex: "#FF6B6B" },
      { name: "Black", hex: "#000000" },
    ],
    sizes: [
      { name: "US 7", available: true },
      { name: "US 8", available: true },
      { name: "US 9", available: true },
      { name: "US 10", available: true },
      { name: "US 11", available: true },
    ],
  },
  {
    slug: "court-master",
    name: "Court Master",
    description: "Master every court. The Court Master provides exceptional traction, stability, and comfort for tennis, basketball, and other court sports.",
    shortDescription: "Multi-court performance shoes",
    price: 189,
    rating: 4.7,
    reviewCount: 389,
    images: [
      "/images/products/court-master-1.jpg",
      "/images/products/court-master-2.jpg",
      "/images/products/court-master-3.jpg",
    ],
    category: "Basketball" as const,
    brand: "LUXE",
    stock: 36,
    tags: ["basketball", "tennis", "court", "multi-sport"],
    featured: false,
    newArrival: false,
    bestSeller: false,
    colors: [
      { name: "White/Green", hex: "#FFFFFF" },
      { name: "Black/Orange", hex: "#000000" },
    ],
    sizes: [
      { name: "US 8", available: true },
      { name: "US 9", available: true },
      { name: "US 10", available: true },
      { name: "US 11", available: true },
      { name: "US 12", available: true },
    ],
  },
  {
    slug: "cross-trainer",
    name: "Cross Trainer",
    description: "One shoe, every workout. The Cross Trainer is designed for versatility, providing support and comfort for running, lifting, and everything in between.",
    shortDescription: "Versatile cross-training shoes",
    price: 159,
    rating: 4.5,
    reviewCount: 567,
    images: [
      "/images/products/cross-trainer-1.jpg",
      "/images/products/cross-trainer-2.jpg",
    ],
    category: "Training" as const,
    brand: "LUXE",
    stock: 58,
    tags: ["training", "cross-fit", "versatile", "gym"],
    featured: false,
    newArrival: false,
    bestSeller: false,
    colors: [
      { name: "Black", hex: "#000000" },
      { name: "Gray", hex: "#6B7280" },
      { name: "Blue", hex: "#3B82F6" },
    ],
    sizes: [
      { name: "US 7", available: true },
      { name: "US 8", available: true },
      { name: "US 9", available: true },
      { name: "US 10", available: true },
      { name: "US 11", available: true },
    ],
  },
  {
    slug: "minimalist-pro",
    name: "Minimalist Pro",
    description: "Less is more. The Minimalist Pro features a sleek, streamlined design with premium materials and exceptional comfort for the modern minimalist.",
    shortDescription: "Sleek minimalist design",
    price: 179,
    rating: 4.8,
    reviewCount: 423,
    images: [
      "/images/products/minimalist-1.jpg",
      "/images/products/minimalist-2.jpg",
      "/images/products/minimalist-3.jpg",
    ],
    category: "Lifestyle" as const,
    brand: "LUXE",
    stock: 44,
    tags: ["minimalist", "sleek", "modern", "lifestyle"],
    featured: true,
    newArrival: true,
    bestSeller: false,
    colors: [
      { name: "White", hex: "#FFFFFF" },
      { name: "Black", hex: "#000000" },
      { name: "Gray", hex: "#9CA3AF" },
    ],
    sizes: [
      { name: "US 7", available: true },
      { name: "US 8", available: true },
      { name: "US 9", available: true },
      { name: "US 10", available: true },
      { name: "US 11", available: true },
    ],
  },
];

async function seedDatabase() {
  try {
    await connectDB();
    console.log('Connected to MongoDB');

    // Clear existing products
    await Product.deleteMany({});
    console.log('Cleared existing products');

    // Insert mock products
    await Product.insertMany(mockProducts);
    console.log('Inserted mock products');

    console.log('Database seeded successfully!');
    process.exit(0);
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
}

seedDatabase();
